name: taghyeer_spend_arc
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fpdart: ^1.2.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  get_it: ^9.2.1
  sqflite: ^2.4.2
  path: ^1.9.1
  connectivity_plus: ^7.1.1
  uuid: ^4.5.3
  go_router: ^17.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.5
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true

  shaders:
    - shaders/spending_glow.frag
    - shaders/sync_shimmer.frag
    - shaders/particle_field.frag
